name: Build Tiny11 26H2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        shell: pwsh
        run: |
          Get-PSDrive C
          Remove-Item "C:\Program Files\Android" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "C:\Program Files\dotnet" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "C:\Program Files (x86)\Microsoft\EdgeUpdate" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "C:\ProgramData\chocolatey" -Recurse -Force -ErrorAction SilentlyContinue
          Remove-Item "C:\hostedtoolcache" -Recurse -Force -ErrorAction SilentlyContinue
          Get-PSDrive C

      - name: Download Windows 11 26H2
        shell: pwsh
        run: |
          $url = 'https://software.download.prss.microsoft.com/dbazure/Windows11_Client_x64_en-us_26300_9457.iso?t=75006e8e-e751-4c1a-a447-87e68c3527b6&P1=1791019858&P2=602&P3=2&P4=j9x9VOZZ0DA9a98Doq%2BguHnzfcqf8k76ola0pVr7Nz7iHYKNxDz2QaqPzwqDpbLa5Bv5r6U5C10%2Ft2OpYNZ3zuW%2FuXN3ZSAbtXLt9%2BRGerhQFl7p6nWeUcLEoQazqkr9OwKU%2FMPK8MvDXXQ9iaN8Qw8KsgxrLra6s8SHWq1JK0CzH%2BrMTYsu0gTJ2ZMYOuWT%2BOu8%2BoQpMTFrodF5Z9%2BdqOSoGi77h5x73aiM6y6rAjRR2lKLDEks4qZmMFi5oX58%2FakXfpHlf4IjIntITVzcNfjHgjlhZv52BF%2F1L1Bh4BqC2hk0uWamd3IrTagNreVeee6LbmW5EzaI3CuvbVaJOQ%3D%3D'
          curl.exe -L --fail --retry 3 --retry-delay 5 `
            -o "$env:RUNNER_TEMP\Win11.iso" `
            "$url"

      - name: Check ISO
        shell: pwsh
        run: |
          Get-Item "$env:RUNNER_TEMP\Win11.iso" |
            Select-Object Name,Length

      - name: Mount ISO
        shell: pwsh
        run: |
          Mount-DiskImage "$env:RUNNER_TEMP\Win11.iso"
          $disk = Get-DiskImage "$env:RUNNER_TEMP\Win11.iso" | Get-Volume
          $drive = $disk.DriveLetter
          echo "ISO_DRIVE=$drive" >> $env:GITHUB_ENV
          Write-Host "ISO mounted at $drive`:"

      - name: Run Tiny11
        shell: powershell
        run: |
          # Pass 6 (Windows 11 Pro) into the script stdin
          "6" | powershell.exe -ExecutionPolicy Bypass -File .\tiny11maker.ps1 `
            -ISO $env:ISO_DRIVE `
            -SCRATCH C

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: tiny11-26h2
          path: tiny11.iso
          compression-level: 0
          retention-days: 1
